= Configuring the datasource

include::./includes/attributes.adoc[]
:diataxis-type: reference
:categories: Database

== Datasource

You can find all the information about how to configure a datasource in Quarkus in https://quarkus.io/guides/datasource[the official Quarkus documentation].

The `db-kind` used by this extension is `sqlite` so a configuration defining a default SQLite datasource looks like:

[source,properties,subs=attributes+]
----
quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=... <1>
----
<1> See below for SQLite JDBC URLs.

== JDBC URL

SQLite only runs as an embedded database.

You can specify connection details using the JDBC URL, or use the defaults.

An SQLite JDBC URL looks like the following:


`jdbc:sqlite:[path]/[name][?key=value...]`

Example:: `jdbc:sqlite:/home/user/mydatabase.db`

SQLite also supports in-memory database management, which does not create any database files.
To use an in-memory database, specify the following JDBC URL:

[source,java,subs=attributes+]
----
jdbc:sqlite::memory:
----

The https://www.sqlite.org/uri.html[official documentation] and https://www.sqlite.org/c3ref/open.html#urifilenameexamples[URI Examples] go into more details and list optional parameters as well.

Please refer at this documentation for additional supported mechanisms for providing a https://github.com/roastedroot/sqlite4j/blob/main/USAGE.md#reading-database-files-in-classpaths-or-network-read-only[database URL].

== Full configuration

This Quarkus extension is built on top of link:https://github.com/roastedroot/sqlite4j[SQLite4j].
Refer to its documentation for all the possible configuration options.
